# Site settings
title: Jerematic
email: jsteinert@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A contribution to the global collective; notes about linux, devops, programming, and technology.  
baseurl: ""
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jerematic
github_username:  jerematic

# Build settings
markdown: kramdown
